.catalog:
  name: "weblogic"
  version: "CVE-2018-2628"
  description: "CVE-2018-2628"
  uuid: 1
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should listen on?"
    default: 7001
    required: true