version: '2'
services:
 glassfish:
   image: gjpt1/glassfish:SSV-90437
   volumes:
    - www:/var/www/html
    - ./conf:/etc/nginx
   ports:
    - "${PORT}:8080"
    - "${PORT_ADMIN}:4848"
   environment:
    - ADMIN_PASSWORD=${PASSWORD}