version: '2'
services:
 web:
   image: gjpt1/thinkphp:5.0.9
   depends_on:
    - mysql
   ports:
    - "${PORT}:80"
 mysql:
   image: gjpt1/mysql:5-thinkphp
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cat