version: '2'

catalog:
  name: bitbucket
  version: 5.6.1
  description: Git Server
  questions:
    - variable: BITBUCKET_PORT
      label: Port
      default: 80
      required: true
      type: int



