.catalog:
  name: "shellshock"
  version: "CVE-2014-7169"
  description: "https://github.com/Medicean/VulApps/tree/master/b/bash/shellshock2_CVE-2014-7169"
  uuid: 1
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should listen on?"
    default: 80
    required: true
