version: '2'
services:
 web:
   image: gjpt1/joomla:CVE-2017-8917
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST= mysql:3306
    - JOOMLA_DB_USER= ${JOOMLA_DB_USER}
    - JOOMLA_DB_PASSWORD= ${JOOMLA_DB_PASSWORD}
    - JOOMLA_DB_NAME= joomla
   ports:
    - "${PORT}:80"
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=${PASSWORD}
